# Copy to .github/workflows/deploy.yml when your Git token has the `workflow` scope
# (e.g. `gh auth refresh -s workflow`), then push.
name: Deploy BlueOS Extension Image

on:
  push:
  workflow_dispatch:

jobs:
  deploy-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Clear Docker cache
        run: |
          docker builder prune -f
          docker buildx prune -f

      - name: Deploy BlueOS Extension
        uses: BlueOS-community/Deploy-BlueOS-Extension@v1.2.0
        with:
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: "blueos-timelapse-controller"
          build-platforms: "linux/arm/v7,linux/arm64/v8"
          author: ${{ vars.MY_NAME }}
          author-email: ${{ vars.MY_EMAIL }}
          maintainer: ${{ vars.ORG_NAME }}
          maintainer-email: ${{ vars.ORG_EMAIL }}
